name: EclipticStructure
version: '${project.version}'
main: org.wolflink.minecraft.plugin.eclipticstructure.EclipticStructure
api-version: '1.20'
authors: [MikkoAyaka]
depend:
  - FastAsyncWorldEdit
  - PlaceholderAPI
  - WolfirdFramework
  - DecentHolograms
